In [1]:
import torch
import numpy as np # linear algebra

In [2]:
torch.__version__

'2.0.0+cpu'

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
x = torch.from_numpy(arr)

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
x.dtype

torch.int64

In [12]:
arr2d = np.arange(0.0, 12.0)

In [13]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
x

tensor([1, 2, 3, 4, 5])

In [18]:
arr[0] = 99

In [19]:
x

tensor([99,  2,  3,  4,  5])

In [20]:
my_arr = np.arange(0, 10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(my_arr)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)

In [23]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_arr[0] = 9999

In [26]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
new_arr = np.array([1, 2, 3])

In [30]:
new_arr.dtype

dtype('int64')

In [31]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [32]:
my_tensor = torch.Tensor(new_arr)

In [33]:
my_tensor.dtype

torch.float32

In [34]:
torch.empty(4, 2)

tensor([[-1.0598e-23,  4.4023e-41],
        [-1.0598e-23,  4.4023e-41],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [35]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [36]:
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
torch.arange(0, 18, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [39]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [40]:
torch.linspace(0, 18, 12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [41]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [42]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [43]:
my_tensor = torch.tensor([1, 2, 3])

In [44]:
my_tensor.dtype

torch.int64

In [45]:
my_tensor.type()

'torch.LongTensor'

In [46]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
my_tensor = my_tensor.type(torch.int32)

In [48]:
my_tensor.dtype

torch.int32

In [49]:
torch.rand(4, 3)

tensor([[0.2313, 0.5829, 0.5382],
        [0.8951, 0.9628, 0.7690],
        [0.4121, 0.0560, 0.4776],
        [0.4364, 0.3516, 0.9840]])

In [50]:
torch.randn(4, 3)

tensor([[ 1.4001, -0.4063,  0.2867],
        [ 1.0935,  1.0354, -1.0496],
        [ 1.6632, -0.4035, -1.2202],
        [-1.2624,  0.1222, -0.4428]])

In [51]:
torch.randint(low=0, high=10, size=(5, 5))

tensor([[0, 0, 3, 3, 5],
        [2, 1, 1, 1, 5],
        [8, 7, 3, 2, 0],
        [8, 4, 5, 2, 3],
        [1, 1, 9, 9, 5]])

In [52]:
torch.randint(low=0, high=11, size=(5, 5))

tensor([[ 2,  9, 10,  3,  4],
        [ 5,  1,  6,  0,  8],
        [ 1,  3,  4,  3,  1],
        [ 7, 10,  7,  3,  8],
        [ 2,  6,  8,  4,  0]])

In [53]:
x = torch.zeros(2, 5)

In [54]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [55]:
x.shape

torch.Size([2, 5])

In [56]:
torch.rand_like(x)

tensor([[0.6765, 0.0238, 0.9648, 0.6464, 0.7494],
        [0.5791, 0.9606, 0.4662, 0.2291, 0.6949]])

In [57]:
torch.randn_like(x)

tensor([[-0.5313, -0.8526, -1.5309, -0.1469,  0.7011],
        [-1.7196, -0.1697,  0.7322, -0.1635, -1.8718]])

In [58]:
torch.randint_like(x, low=0, high=11)

tensor([[10.,  7.,  7.,  5.,  0.],
        [ 6.,  9.,  7.,  1.,  4.]])

In [59]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [60]:
torch.rand(2, 3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [61]:
torch.rand(2, 3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])