In [1]:
import numpy as np # linear algebra
import torch

In [2]:
x = torch.arange(6).reshape(3, 2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1, 1]

tensor(3)

In [5]:
type(x[1, 1])

torch.Tensor

In [6]:
x[:, 1]

tensor([1, 3, 5])

In [7]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [8]:
x = torch.arange(10)

In [9]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x = x.reshape(2, 5)

In [15]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
x = torch.arange(10)

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x.shape

torch.Size([10])

In [19]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
z = x.view(2, 5)

In [21]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
x[0] = 9999

In [23]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [25]:
x = torch.arange(10)

In [26]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x.shape

torch.Size([10])

In [28]:
# Infer what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
a = torch.tensor([1., 2., 3.])

In [31]:
b = torch.tensor([4., 5., 6.])

In [32]:
a

tensor([1., 2., 3.])

In [33]:
b

tensor([4., 5., 6.])

In [34]:
a.dtype

torch.float32

In [35]:
b.type

<function Tensor.type>

In [36]:
b.dtype

torch.float32

In [37]:
a + b

tensor([5., 7., 9.])

In [38]:
torch.add(a, b)

tensor([5., 7., 9.])

In [39]:
# a = a + b

a.mul(b)

tensor([ 4., 10., 18.])

In [40]:
a

tensor([1., 2., 3.])

In [41]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [42]:
a

tensor([ 4., 10., 18.])