In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)


In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1]

1

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [12]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
new_arr = arr / 2

In [14]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy[:] = 1000

In [26]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
# INDEXING on 2d array

In [29]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d[1]

array([20, 25, 30])

In [33]:
arr_2d[1][1]

25

In [34]:
arr_2d[1, 1]

25

In [35]:
arr_2d[2, 2]

45

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [38]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [39]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr = np.arange(1, 11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
bool_arr = arr > 4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr == 2]

array([2])

In [48]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])